// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjexmvniyunblnhvbkzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZXhtdm5peXVuYmxuaHZia3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzQzMTAsImV4cCI6MjA2MzkxMDMxMH0.yp6D_ysP6H3uXq_kESBj_MrJREHs1ptwyDv69Ed4qtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);